### ISSUE TITLE
New paper on FL with label skew

### ISSUE THREAD

**Issue by ShikunLi** [marswhu/HFL_Survey#3]
Hello maintainers,

Super thanks for updating this nice list for HFL!
Here's a paper of mine (at ACM MM'23 as an oral presentation) that tries to address the label distribution skew problem in federated learning with a simple regularization:

Federated Learning with Label-Masking Distillation (https://dl.acm.org/doi/abs/10.1145/3581783.3611984)
Jianghu Lu, Shikun Li, Kexin Bao, Pengju Wang, Zhenxing Qian, Shiming Ge.
ACM MM 2023

It'll be awesome if you could include this in the list. 

Thanks!

**Comment by marswhu** [comment]
Thanks. Just merged.
